<!DOCTYPE html>
<html>
<head>
<title>Happy 16th Windaaa ğŸ’œ</title>
<style>
body {
  text-align:center;
  font-family: Arial;
  background: linear-gradient(to right, #d5b6ff, #f3e8ff);
  color:#5a3e85;
}

.box {
  background: rgba(255,255,255,0.6);
  padding:20px;
  border-radius:20px;
  width:85%;
  margin:auto;
  margin-top:20px;
  box-shadow:0 5px 15px rgba(150, 111, 214, 0.5);
}

button {
  padding:10px 20px;
  margin:10px;
  border:none;
  border-radius:12px;
  cursor:pointer;
  background:#b57edc;
  color:white;
  font-weight:bold;
}

#letter {
  display:none;
  background:white;
  color:#5a3e85;
  padding:20px;
  border-radius:15px;
  margin-top:15px;
}

#giftGame {
  font-size:45px;
  cursor:pointer;
}

h1 {
  margin-top:40px;
  font-size:38px;
}
</style>
</head>

<body>

<h1>ğŸ’œ HAPPY 16th BIRTHDAY WINDAAA ğŸ’œ</h1>

<div class="box">
<h2>â³ Hitung Mundur</h2>
<p id="countdown"></p>
</div>

<div class="box">
<h2>ğŸ® Game Klik Kado</h2>
<p>Klik kado sampai dapat kejutan buat Windaaa ğŸ˜œ</p>
<div id="giftGame">ğŸ</div>
<p id="gameText"></p>
</div>

<div class="box">
<h2>ğŸ’Œ Surat Untuk Windaaa</h2>
<button onclick="openLetter()">Buka Surat ğŸ’–</button>

<div id="letter">
Selamat ulang tahun yang ke-16, Windaaa ğŸ’œ<br><br>

Aku tau kamu sering merasa harus kuat,
harus berhasil, dan nggak boleh gagal.
Padahal kamu juga manusia yang boleh capek.<br><br>

Kalau suatu hari rasanya berat,
semoga kamu ingat masih ada hal-hal baik
yang selalu berpihak sama kamu.<br><br>

Dan terima kasih,
karena kamu pernah jadi bagian
yang ngisi hari-hari aku.
Itu nggak pernah biasa buatku. ğŸ’«<br><br>

Sweet sixteen.
</div>

</div>

<script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>

<script>
// TANGGAL ULTAH WINDAAA
var birthday = new Date("Feb 21, 2026 00:00:00").getTime();

var x = setInterval(function() {
  var now = new Date().getTime();
  var distance = birthday - now;

  var days = Math.floor(distance / (1000 * 60 * 60 * 24));

  if (distance > 0) {
    document.getElementById("countdown").innerHTML =
    days + " hari lagi menuju 16 tahun ğŸ’œâœ¨";
  } else {
    document.getElementById("countdown").innerHTML =
    "HARI INI WINDAAA ULTAH ğŸ‰ğŸ’œ";
    confetti();
  }
}, 1000);

// GAME
var klik = 0;
document.getElementById("giftGame").onclick = function() {
  klik++;
  if (klik < 6) {
    document.getElementById("gameText").innerHTML =
    "Belum dapet ğŸ˜œ klik lagi!";
  } else {
    document.getElementById("gameText").innerHTML =
    "YEEE dapet kebahagiaan + rejeki + nilai bagus ğŸ‰ğŸ’œ";
    confetti();
  }
};

// SURAT
function openLetter(){
  document.getElementById("letter").style.display = "block";
  confetti();
}
</script>

</body>
</html>
